-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema DEPA_GROUP_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DEPA_GROUP_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DEPA_GROUP_1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `DEPA_GROUP_1` ;

-- -----------------------------------------------------
-- Table `DEPA_GROUP_1`.`LOCATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEPA_GROUP_1`.`LOCATION` (
  `LOCATION_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `LATITUDE` DOUBLE NOT NULL,
  `LONGITUDE` DOUBLE NOT NULL,
  `ZIPCODE` INT(11) NULL DEFAULT NULL,
  `NEIGHBORHOOD` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`LOCATION_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DEPA_GROUP_1`.`COMPLAINTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEPA_GROUP_1`.`COMPLAINTS` (
  `COMPLAINT_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `COMPLAINT_TYPE` VARCHAR(100) NULL DEFAULT NULL,
  `ADDRESS` VARCHAR(100) NULL DEFAULT NULL,
  `STREET_NAME` VARCHAR(40) NULL DEFAULT NULL,
  `COMPLAINT_DETAIL` TEXT NULL DEFAULT NULL,
  `COMPLAINT_DATE` DATE NULL DEFAULT NULL,
  `MODIFIED_DATE` DATE NULL DEFAULT NULL,
  `LOCATION_ID` INT(11) NULL,
  PRIMARY KEY (`COMPLAINT_ID`),
  INDEX `fk_COMPLAINTS_LOCATION1_idx` (`LOCATION_ID` ASC) VISIBLE,
  CONSTRAINT `fk_COMPLAINTS_LOCATION1`
    FOREIGN KEY (`LOCATION_ID`)
    REFERENCES `DEPA_GROUP_1`.`LOCATION` (`LOCATION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8192
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DEPA_GROUP_1`.`CRIME`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEPA_GROUP_1`.`CRIME` (
  `CRIME_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CASE_NUMBER` VARCHAR(10) NULL DEFAULT NULL,
  `CRIME_DATE` DATETIME NULL DEFAULT NULL,
  `BLOCK` VARCHAR(150) NULL DEFAULT NULL,
  `IUCR` VARCHAR(10) NULL DEFAULT NULL,
  `PRIMARY_TYPE` VARCHAR(80) NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
  `LOCATION_DESCRIPTION` VARCHAR(80) NULL DEFAULT NULL,
  `ARREST` VARCHAR(10) NULL DEFAULT NULL,
  `DOMESTIC` VARCHAR(10) NULL DEFAULT NULL,
  `BEAT` INT(11) NULL DEFAULT NULL,
  `DISTRICT` INT(11) NULL DEFAULT NULL,
  `WARD` INT(11) NULL DEFAULT NULL,
  `COMMUNITY_AREA` INT(11) NULL DEFAULT NULL,
  `FBI_CODE` VARCHAR(10) NULL DEFAULT NULL,
  `YEAR` INT(11) NULL DEFAULT NULL,
  `UPDATED_ON` DATETIME NULL DEFAULT NULL,
  `LOCATION_ID` INT(11) NULL,
  PRIMARY KEY (`CRIME_ID`),
  INDEX `fk_CRIME_LOCATION1_idx` (`LOCATION_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CRIME_LOCATION1`
    FOREIGN KEY (`LOCATION_ID`)
    REFERENCES `DEPA_GROUP_1`.`LOCATION` (`LOCATION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1638376
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DEPA_GROUP_1`.`VIOLATIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEPA_GROUP_1`.`VIOLATIONS` (
  `VIOLATION_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DOCKET_NUMBER` VARCHAR(20) NULL DEFAULT NULL,
  `TICKET_NUMBER` VARCHAR(20) NULL DEFAULT NULL,
  `ADDRESS` VARCHAR(100) NULL DEFAULT NULL,
  `STREET_NUMBER` INT(11) NULL DEFAULT NULL,
  `STREET_DIRECTION` VARCHAR(5) NULL DEFAULT NULL,
  `STREET_NAME` VARCHAR(50) NULL DEFAULT NULL,
  `STREET_TYPE` VARCHAR(10) NULL DEFAULT NULL,
  `WARD` INT(11) NULL DEFAULT NULL,
  `ISSUING_DEPARTMENT` VARCHAR(40) NULL DEFAULT NULL,
  `HEARING_DATE` DATE NULL DEFAULT NULL,
  `CASE_DISPOSITION` VARCHAR(40) NULL DEFAULT NULL,
  `IMPOSED_FINE` INT(11) NULL DEFAULT NULL,
  `ADMIN_COSTS` INT(11) NULL DEFAULT NULL,
  `LAST_MODIFIED_DATE` DATETIME NULL DEFAULT NULL,
  `VIOLATION_DATE` DATETIME NULL DEFAULT NULL,
  `VIOLATION_CODE` VARCHAR(15) NULL DEFAULT NULL,
  `VIOLATION_DESCRIPTION` TEXT NULL DEFAULT NULL,
  `RESPONDENTS` TEXT NULL DEFAULT NULL,
  `LOCATION_ID` INT(11) NULL,
  PRIMARY KEY (`VIOLATION_ID`),
  INDEX `fk_VIOLATIONS_LOCATION1_idx` (`LOCATION_ID` ASC) VISIBLE,
  CONSTRAINT `fk_VIOLATIONS_LOCATION1`
    FOREIGN KEY (`LOCATION_ID`)
    REFERENCES `DEPA_GROUP_1`.`LOCATION` (`LOCATION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 262141
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DEPA_GROUP_1`.`WEATHER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEPA_GROUP_1`.`WEATHER` (
  `WEATHER_RECORD_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DATE` DATE NOT NULL,
  `STATION` VARCHAR(15) NOT NULL,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  `ELEVATION` DOUBLE NULL DEFAULT NULL,
  `AVG_WIND` DOUBLE NULL DEFAULT NULL,
  `EVAP` DOUBLE NULL DEFAULT NULL,
  `MIN_WATER_PAN_TEMP` DOUBLE NULL DEFAULT NULL,
  `MAX_WATER_PAN_TEMP` DOUBLE NULL DEFAULT NULL,
  `PEAK_GUST_TIME` DOUBLE NULL DEFAULT NULL,
  `PRECIPITATION` DOUBLE NULL DEFAULT NULL,
  `MIN_SOIL_TEMP_BARE_10CM` DOUBLE NULL DEFAULT NULL,
  `MIN_SOIL_TEMP_SOD_10CM` DOUBLE NULL DEFAULT NULL,
  `SNOWFALL` DOUBLE NULL DEFAULT NULL,
  `SNOW_DEPTH` DOUBLE NULL DEFAULT NULL,
  `MAX_SOIL_TEMP_BARE_10CM` DOUBLE NULL DEFAULT NULL,
  `MAX_SOIL_TEMP_SOD_10CM` DOUBLE NULL DEFAULT NULL,
  `TEMP_AVG` DOUBLE NULL DEFAULT NULL,
  `TEMP_MAX` DOUBLE NULL DEFAULT NULL,
  `TEMP_MIN` DOUBLE NULL DEFAULT NULL,
  `TEMP_TIME_OBS` DOUBLE NULL DEFAULT NULL,
  `WIND_DIR_2MIN` DOUBLE NULL DEFAULT NULL,
  `WIND_DIR_5MIN` DOUBLE NULL DEFAULT NULL,
  `WIND_MOVEMENT_24HR` DOUBLE NULL DEFAULT NULL,
  `WTR_EQ_SNW_GRND` DOUBLE NULL DEFAULT NULL,
  `WTR_EQ_SNW_FALL` DOUBLE NULL DEFAULT NULL,
  `WIND_SPD_2MIN` DOUBLE NULL DEFAULT NULL,
  `WIND_SPD_5MIN` DOUBLE NULL DEFAULT NULL,
  `WT_FOG` DOUBLE NULL DEFAULT NULL,
  `WT_HEAVY_FOG` DOUBLE NULL DEFAULT NULL,
  `WT_THUNDER` DOUBLE NULL DEFAULT NULL,
  `WT_ICE_PELLETS` DOUBLE NULL DEFAULT NULL,
  `WT_HAIL` DOUBLE NULL DEFAULT NULL,
  `WT_GLAZE` DOUBLE NULL DEFAULT NULL,
  `WT_SMOKE` DOUBLE NULL DEFAULT NULL,
  `WT_BLOWING_SNOW` DOUBLE NULL DEFAULT NULL,
  `WT_HIGH_WINDS` DOUBLE NULL DEFAULT NULL,
  `LOCATION_ID` INT(11) NULL,
  PRIMARY KEY (`WEATHER_RECORD_ID`),
  INDEX `fk_WEATHER_LOCATION_idx` (`LOCATION_ID` ASC) VISIBLE,
  CONSTRAINT `fk_WEATHER_LOCATION`
    FOREIGN KEY (`LOCATION_ID`)
    REFERENCES `DEPA_GROUP_1`.`LOCATION` (`LOCATION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 262141
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
