USE depa_group_1_staging;

INSERT INTO DEPA_GROUP_1.LOCATION
SELECT NULL AS LOCATION_ID,
	   `latitude` AS LATITUDE,
	   `longitude` AS LONGITUDE,
	   `zip` AS ZIPCODE,
	   `Neighborhood` AS NEIGHBORHOOD
FROM location_staging;

INSERT INTO DEPA_GROUP_1.WEATHER
SELECT NULL,
	   DATE,
	   STATION,
	   NAME,
	   ELEVATION,
	   AWND,
	   EVAP,
	   MNPN,
	   MXPN,
	   PGTM,
	   PRCP,
	   SN32,
	   SN52,
	   SNOW,
	   SNWD,
	   SX32,
	   SX52,
	   TAVG,
	   TMAX,
	   TMIN,
	   TOBS,
	   WDF2,
	   WDF5,
	   WDMV,
	   WESD,
	   WESF,
	   WSF2,
	   WSF5,
	   WT01,
	   WT02,
	   WT03,
	   WT04,
	   WT05,
	   WT06,
	   WT08,
	   WT09,
	   WT11,
       L.LOCATION_ID
FROM chicago_weather_staging AS C LEFT JOIN
	 DEPA_GROUP_1.LOCATION AS L ON ROUND(C.LATITUDE, 3) = L.LATITUDE AND
								   ROUND(C.LATITUDE, 3) = L.LONGITUDE;

INSERT INTO DEPA_GROUP_1.VIOLATIONS
SELECT NULL AS VIOLATION_ID,
	   `DOCKET.NUMBER` AS DOCKET_NUMBER,
	   `NOV.NUMBER` AS TICKET_NUMBER,
	   `ADDRESS` AS ADDRESS,
	   `STREET.NUMBER` AS STREET_NUMBER,
	   `STREET.DIRECTION` AS STREET_DIRECTION,
	   `STREET.NAME` AS STREET_NAME,
	   `STREET.TYPE` AS STREET_TYPE,
	   `WARD` AS WARD,
	   `ISSUING.DEPARTMENT` AS ISSUING_DEPARTMENT,
	   STR_TO_DATE(`HEARING.DATE`, '%m/%d/%Y') AS HEARING_DATE,
	   `CASE.DISPOSITION` AS CASE_DISPOSITION,
	   `IMPOSED.FINE` AS IMPOSED_FINE,
	   `ADMIN.COSTS` AS ADMIN_COSTS,
	   STR_TO_DATE(`LAST.MODIFIED.DATE`, '%m/%d/%Y %l:%i:%s %p') AS LAST_MODIFIED_DATE,
	   STR_TO_DATE(`VIOLATION.DATE`, '%m/%d/%Y %l:%i:%s %p') AS VIOLATION_DATE,
	   `VIOLATION.CODE` AS VIOLATION_CODE,
	   `VIOLATION.DESCRIPTION` AS VIOLATION_DESCRIPTION,
	   `RESPONDENTS` AS RESPONDENTS,
       L.LOCATION_ID
FROM chicago_violations_staging AS C LEFT JOIN
	 DEPA_GROUP_1.LOCATION AS L ON ROUND(C.LATITUDE, 3) = L.LATITUDE AND
								   ROUND(C.LATITUDE, 3) = L.LONGITUDE;

INSERT INTO DEPA_GROUP_1.CRIME
SELECT NULL AS CRIME_ID,
	   `Case.Number` AS CASE_NUMBER,
	   STR_TO_DATE(`Date`, '%m/%d/%Y %l:%i:%s %p') AS CRIME_DATE,
	   `Block` AS BLOCK,
	   `IUCR` AS IUCR,
	   `Primary.Type` AS PRIMARY_TYPE,
	   `Description` AS DESCRIPTION,
	   `Location.Description` AS LOCATION_DESCRIPTION,
	   `Arrest` AS ARREST,
	   `Domestic` AS DOMESTIC,
	   `Beat` AS BEAT,
	   `District` AS DISTRICT,
	   `Ward` AS WARD,
	   `Community.Area` AS COMMUNITY_AREA,
	   `FBI.Code` AS FBI_CODE,
	   `Year` AS YEAR,
	   STR_TO_DATE(`Updated.On`, '%m/%d/%Y %l:%i:%s %p') AS UPDATED_ON,
       L.LOCATION_ID
FROM chicago_crime_staging AS C LEFT JOIN
	 DEPA_GROUP_1.LOCATION AS L ON ROUND(C.LATITUDE, 3) = L.LATITUDE AND
								   ROUND(C.LATITUDE, 3) = L.LONGITUDE;

INSERT INTO DEPA_GROUP_1.COMPLAINTS
SELECT NULL AS COMPLAINT_ID,
	   `COMPLAINT.TYPE` AS COMPLAINT_TYPE,
	   `ADDRESS` AS ADDRESS,
	   `STREET.NAME` AS STREET_NAME,
	   `COMPLAINT.DETAIL` AS COMPLAINT_DETAIL,
	   STR_TO_DATE(`Complaint_date`, '%Y-%m-%d') AS COMPLAINT_DATE,
	   STR_TO_DATE(`Modified_date`, '%Y-%m-%d') AS MODIFIED_DATE,
       L.LOCATION_ID
FROM chicago_complaints_staging AS C LEFT JOIN
	 DEPA_GROUP_1.LOCATION AS L ON ROUND(C.LATITUDE, 3) = L.LATITUDE AND
								   ROUND(C.LATITUDE, 3) = L.LONGITUDE;
